version: "3.9"
services:
  db:
    image: postgres:15.1
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432 #postgres default port
    environment:
      POSTGRES_DB: offeraid
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
volumes:
  postgres_data:
