CREATE TABLE roles
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       TEXT                                     NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    CONSTRAINT pk_roles PRIMARY KEY (id),
    CONSTRAINT uc_roles_name UNIQUE (name)
);

INSERT INTO roles(name)
VALUES ('USER'),
       ('ADMIN');

CREATE TABLE users
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email      TEXT                                     NOT NULL,
    password   TEXT                                     NOT NULL,
    name       TEXT                                     NOT NULL,
    enabled    BOOLEAN                     DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uc_users_email UNIQUE (email)
);

CREATE TABLE users_roles
(
    user_id INTEGER NOT NULL,
    role_id INTEGER NOT NULL,
    CONSTRAINT pk_users_roles PRIMARY KEY (role_id, user_id),
    CONSTRAINT fk_users_roles_on_users FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_users_roles_on_roles FOREIGN KEY (role_id) REFERENCES roles (id)
);

CREATE TABLE verification_tokens
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token       TEXT                                     NOT NULL,
    user_id     INTEGER                                  NOT NULL,
    expiry_date TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    updated_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    CONSTRAINT pk_verification_tokens PRIMARY KEY (id),
    CONSTRAINT fk_verification_tokens_on_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE areas
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       TEXT                                     NOT NULL,
    url        TEXT                                     NOT NULL,
    usable     BOOL                                     NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE                       DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE                       DEFAULT NOW(),
    CONSTRAINT pk_areas PRIMARY KEY (id),
    CONSTRAINT uc_areas_url UNIQUE (url)
);

CREATE TABLE categories
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       TEXT                                     NOT NULL,
    url        TEXT                                     NOT NULL,
    usable     BOOL                                     NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT uc_categories_url UNIQUE (url)
);

CREATE TABLE offers
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     INTEGER,
    area_id     INTEGER,
    category_id INTEGER,
    title       TEXT,
    body        TEXT,
    active      BOOLEAN,
    deleted     BOOLEAN,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_offers PRIMARY KEY (id),
    CONSTRAINT fk_offers_on_area FOREIGN KEY (area_id) REFERENCES areas (id),
    CONSTRAINT fk_offers_on_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT fk_offers_on_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE user_favorite_offer
(
    user_id    INTEGER NOT NULL,
    offer_id INTEGER NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    CONSTRAINT pk_user_favorite_offer PRIMARY KEY (user_id, offer_id),
    CONSTRAINT fk_user_favorite_offer_on_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_favorite_offer_on_offer FOREIGN KEY (user_id) REFERENCES offers (id) ON DELETE CASCADE
);
